services:
  postgres:
    image: postgres:16
    container_name: tf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pfuser
      POSTGRES_PASSWORD: pfpass
      POSTGRES_DB: pfdb
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfuser -d pfdb || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: tf-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI http://localhost:8025
